// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/commands/blame/blame.go
//
// Generated by this command:
//
//	mockgen -package=mockblame -source=pkg/commands/blame/blame.go -destination=./mocks/blame/blame.go
//

// Package mockblame is a generated GoMock package.
package mockblame

import (
	context "context"
	reflect "reflect"

	sdcpb "github.com/sdcio/sdc-protos/sdcpb"
	gomock "go.uber.org/mock/gomock"
)

// MockBlameFilterClient is a mock of BlameFilterClient interface.
type MockBlameFilterClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlameFilterClientMockRecorder
	isgomock struct{}
}

// MockBlameFilterClientMockRecorder is the mock recorder for MockBlameFilterClient.
type MockBlameFilterClientMockRecorder struct {
	mock *MockBlameFilterClient
}

// NewMockBlameFilterClient creates a new mock instance.
func NewMockBlameFilterClient(ctrl *gomock.Controller) *MockBlameFilterClient {
	mock := &MockBlameFilterClient{ctrl: ctrl}
	mock.recorder = &MockBlameFilterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlameFilterClient) EXPECT() *MockBlameFilterClientMockRecorder {
	return m.recorder
}

// GetBlameTree mocks base method.
func (m *MockBlameFilterClient) GetBlameTree(ctx context.Context, namespace, device string) (*sdcpb.BlameTreeElement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlameTree", ctx, namespace, device)
	ret0, _ := ret[0].(*sdcpb.BlameTreeElement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlameTree indicates an expected call of GetBlameTree.
func (mr *MockBlameFilterClientMockRecorder) GetBlameTree(ctx, namespace, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlameTree", reflect.TypeOf((*MockBlameFilterClient)(nil).GetBlameTree), ctx, namespace, device)
}
