# Copyright 2024 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2
project_name: kubectl-sdcio
builds:
  - id: kubectl-sdcio
    binary: kubectl-sdcio
    main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - ./kubectl_complete-sdcio
nfpms:
  - id: kubectl-sdcio
    package_name: kubectl-sdcio
    vendor: SDC
    homepage: https://github.com/sdcio/kubectl-sdcio
    maintainer: SDC Team
    description: kubectl plugin for SDC
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./kubectl_complete-sdcio
        dst: /usr/bin/kubectl_complete-sdcio
        file_info:
          mode: 0755
checksum:
  name_template: "checksums.txt"
snapshot: {}
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
  draft: false
  replace_existing_draft: true
  disable: false