// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/commands/apply/apply.go
//
// Generated by this command:
//
//	mockgen -package=mockapply -source=pkg/commands/apply/apply.go -destination=./mocks/apply/apply.go
//

// Package mockapply is a generated GoMock package.
package mockapply

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/sdcio/config-server/apis/config/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockApplyClient is a mock of ApplyClient interface.
type MockApplyClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplyClientMockRecorder
	isgomock struct{}
}

// MockApplyClientMockRecorder is the mock recorder for MockApplyClient.
type MockApplyClientMockRecorder struct {
	mock *MockApplyClient
}

// NewMockApplyClient creates a new mock instance.
func NewMockApplyClient(ctrl *gomock.Controller) *MockApplyClient {
	mock := &MockApplyClient{ctrl: ctrl}
	mock.recorder = &MockApplyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplyClient) EXPECT() *MockApplyClientMockRecorder {
	return m.recorder
}

// ClearTargetDeviations mocks base method.
func (m *MockApplyClient) ClearTargetDeviations(ctx context.Context, resource *v1alpha1.TargetClearDeviation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTargetDeviations", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTargetDeviations indicates an expected call of ClearTargetDeviations.
func (mr *MockApplyClientMockRecorder) ClearTargetDeviations(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTargetDeviations", reflect.TypeOf((*MockApplyClient)(nil).ClearTargetDeviations), ctx, resource)
}
