// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/commands/deviations/deviations.go
//
// Generated by this command:
//
//	mockgen -package=mockdeviations -source=pkg/commands/deviations/deviations.go -destination=./mocks/deviations/deviations.go
//

// Package mockdeviations is a generated GoMock package.
package mockdeviations

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/sdcio/config-server/apis/config/v1alpha1"
	types "github.com/sdcio/kubectl-sdc/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviationClient is a mock of DeviationClient interface.
type MockDeviationClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeviationClientMockRecorder
	isgomock struct{}
}

// MockDeviationClientMockRecorder is the mock recorder for MockDeviationClient.
type MockDeviationClientMockRecorder struct {
	mock *MockDeviationClient
}

// NewMockDeviationClient creates a new mock instance.
func NewMockDeviationClient(ctrl *gomock.Controller) *MockDeviationClient {
	mock := &MockDeviationClient{ctrl: ctrl}
	mock.recorder = &MockDeviationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviationClient) EXPECT() *MockDeviationClientMockRecorder {
	return m.recorder
}

// ClearTargetDeviations mocks base method.
func (m *MockDeviationClient) ClearTargetDeviations(ctx context.Context, resource *v1alpha1.TargetClearDeviation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTargetDeviations", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTargetDeviations indicates an expected call of ClearTargetDeviations.
func (mr *MockDeviationClientMockRecorder) ClearTargetDeviations(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTargetDeviations", reflect.TypeOf((*MockDeviationClient)(nil).ClearTargetDeviations), ctx, resource)
}

// GetDeviationByName mocks base method.
func (m *MockDeviationClient) GetDeviationByName(ctx context.Context, namespace, deviationName string) (*types.IntentDeviations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviationByName", ctx, namespace, deviationName)
	ret0, _ := ret[0].(*types.IntentDeviations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviationByName indicates an expected call of GetDeviationByName.
func (mr *MockDeviationClientMockRecorder) GetDeviationByName(ctx, namespace, deviationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviationByName", reflect.TypeOf((*MockDeviationClient)(nil).GetDeviationByName), ctx, namespace, deviationName)
}

// GetDeviationsByTarget mocks base method.
func (m *MockDeviationClient) GetDeviationsByTarget(ctx context.Context, namespace, targetName string) (types.Deviations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviationsByTarget", ctx, namespace, targetName)
	ret0, _ := ret[0].(types.Deviations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviationsByTarget indicates an expected call of GetDeviationsByTarget.
func (mr *MockDeviationClientMockRecorder) GetDeviationsByTarget(ctx, namespace, targetName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviationsByTarget", reflect.TypeOf((*MockDeviationClient)(nil).GetDeviationsByTarget), ctx, namespace, targetName)
}
